export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";

export const USER_SIGNIN_REQUEST = "USER_SIGNIN_REQUEST";
export const USER_SIGNIN_SUCCESS = "USER_SIGNIN_SUCCESS";
export const USER_SIGNIN_FAIL = "USER_SIGNIN_FAIL";

export const USER_SIGNOUT = "USER_SIGNOUT";

export const USER_CONTACT_REQUEST = "USER_CONTACT_REQUEST";
export const USER_CONTACT_SUCCESS = "USER_CONTACT_SUCCESS";
export const USER_CONTACT_FAIL = "USER_CONTACT_FAIL";

export const USER_REVIEW_REQUEST = "USER_REVIEW_REQUEST";
export const USER_REVIEW_SUCCESS = "USER_REVIEW_SUCCESS";
export const USER_REVIEW_FAIL = "USER_REVIEW_FAIL";

export const FETCH_USER_REVIEW_SUCCESS = "FETCH_USER_REVIEW_SUCCESS";
